steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-south1-docker.pkg.dev/mindful-phalanx-462010-e0/my-repo1/food:latest',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/mindful-phalanx-462010-e0/my-repo1/food:latest'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'food-frontend',
        '--image',
        'asia-south1-docker.pkg.dev/mindful-phalanx-462010-e0/my-repo1/food:latest',
        '--region',
        'asia-south1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - asia-south1-docker.pkg.dev/mindful-phalanx-462010-e0/my-repo1/food:latest

options:
  logging: CLOUD_LOGGING_ONLY
